# Generated by Django 5.2.4 on 2026-04-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_precio_floatfield_a_decimalfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materiaprima',
            index=models.Index(fields=['stock_actual'], name='mp_stock_actual_idx'),
        ),
        migrations.AddIndex(
            model_name='materiaprima',
            index=models.Index(fields=['stock_actual', 'stock_minimo'], name='mp_stock_minimo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='producto_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock', 'stock_minimo'], name='producto_stock_minimo_idx'),
        ),
    ]
